swagger: "2.0"
info:
  version: 1.0.0
  title: "Astronauts"
  description: API to manage astronauts
  termsOfService: http://swagger.io/terms/
  contact:
    name: Mirko Schicchi
    email: mirko.schicchi@studenti.unitn.it
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: safe-headland-51483.herokuapp.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /astronauts:
    get:
      description: Get all astronauts
      responses:
        200:
          description: OK - All astronauts listed
          schema:
            $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Add a new astronaut
      operationId: addAstronaut
      parameters:
        - name: astronaut
          in: body
          description: new astronaut
          required: true
          schema:
            $ref: '#/definitions/NewAstronaut'
      responses:
        200:
          description: OK - astronaut inserted
          schema:
              $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /astronauts/{id}:
    get:
      description: Get the specific astronaut
      parameters:
        - name: id
          in: path
          description: ID of the astronaut
          required: true
          type: string
      responses:
        200:
          description: OK - astronaut get
          schema:
              $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      description: Update a specific astronaut
      parameters:
      - name: id
        in: path
        description: ID of the astronaut
        required: true
        type: string
      - name: astronaut
        in: body
        description: Astronaut with parameters updated
        required: true
        schema:
          $ref: '#/definitions/NewAstronaut'
      responses:
        200:
          description: OK - astronaut get
          schema:
              $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Delete an astronaut
      parameters:
      - name: id
        in: path
        description: ID of the astronaut
        required: true
        type: string
      responses:
        204:
          description: OK - astronaut deleted
          schema:
              $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'  
definitions:
  Astronaut:
    required:
      - ID
    allOf:
      - $ref: '#/definitions/NewAstronaut'
    properties:
      ID:
        type: integer
        format: int64
  NewAstronaut:
    required:
      - name
      - surname
      - isInSpace
    properties:
      name:
        type: string
      surname:
        type: string
      isInSpace:
        type: boolean
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string